

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: debian-test
  name: debian-test
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: debian-test
  template:
    metadata:
      labels:
        k8s-app: debian-test
    spec:
      containers:
      - name: debian-test
        image: registry.digitalocean.com/pixi/start:master-10 
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
          protocol: TCP
        

---
## ------------------- Debian Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: debian-test
  name: debian-test
spec:
  ports:
    - port: 80
      targetPort: 3000
  type: NodePort
  selector:
    k8s-app: debian-test
